# Generated by Django 4.1.5 on 2023-02-07 12:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablereserv',
            options={'ordering': ('-date', 'time')},
        ),
        migrations.AddField(
            model_name='tablereserv',
            name='date_of_reserv',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablereserv',
            name='date_processed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablereserv',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tablereserv',
            name='user_phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Wrong number', regex='/^\\+380\\d{3}\\d{2}\\d{2}\\d{2}$/')]),
        ),
    ]
