# Generated by Django 4.1.5 on 2023-02-15 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_tablereserv_options_tablereserv_date_of_reserv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereserv',
            name='user_phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Wrong number', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$')]),
        ),
    ]
